#!/bin/bash 
# Copyright (c) Microsoft Corporation
# All rights reserved. 
#
# Licensed under the Apache License, Version 2.0 (the ""License""); you
# may not use this file except in compliance with the License. You may
# obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
# LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR
# A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.
#
# See the Apache Version 2.0 License for specific language governing
# permissions and limitations under the License.
#
# Run this script for a test of the library functions
#
array=( "test_fft" "test_ifft" "test_int16" "test_int32" "test_complex16" "test_complex32" "test_logical" ) #
#
for element in ${array[@]} #
do #    
#
	if [ "$element" != "test_logical" ]; then #
		cp test_fft.infile $element.infile #
	fi #
	# Chance COMPILER=vs to COMPILER=gcc or COMPILER=winddk to change the default compiler
	COMPILER=vs make -B $element.outfile #
done #
#
error="There were no errors!" #
for element in ${array[@]} #
do #
#
	if ! diff  $element.outfile.ground $element.outfile >/dev/null; then #
	echo "Error: $element.outfile does not match $element.outfile.ground" ; error=""  #
	fi	#
done #
#
make clean --silent #
echo "$error" #
rm test_ifft.infile test_int16.infile test_int32.infile test_complex16.infile test_complex32.infile # 
