#!/bin/bash
#Use COMPILER={winddk, vs} to set the compiler

cd transmitter/perf
make -B 
if [[ $? -ne 0 ]]
then
    exit 1
fi
cd ../../receiver/perf
make -B 
if [[ $? -ne 0 ]]
then
    exit 1
fi
cd ../../perf
make -B
if [[ $? -ne 0 ]]
then
    exit 1
fi
EXTRAOPTS='--pipeline --affinity-mask=5 '$EXTRAOPTS make -B
if [[ $? -ne 0 ]]
then
    exit 1
fi
