#!/bin/bash
#Use COMPILER={winddk, vs} to set the compiler

cd transmitter/tests
make -B
if [[ $? -ne 0 ]]
then
    exit 1
fi
cd ../../receiver/tests
make -B
if [[ $? -ne 0 ]]
then
    exit 1
fi
cd ../../tests
if [[ $? -ne 0 ]]
then
    exit 1
fi
make -B

